import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        height: '100%',
        width: '100%',
        paddingTop: 50,
        flexDirection: 'column',
        justifyContent: 'space-between',
        backgroundColor: '#030b10',
    },
    title: {
        color: '#fff',
        fontSize: 24,
        marginBottom: 10,
        textTransform: 'capitalize',
    },
    label: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    text: {
        color: '#fff',
        fontSize: 14,
    },
    section: {
        marginBottom: 10,
    },
    addSpellButton: {
        margin: 5,
        borderRadius: 8,
        overflow: 'hidden',
        flexGrow: 0,
        flexShrink: 0,
        height: 80,
    },
    spellButtonBackground: {
        flex: 1,
        resizeMode: 'contain',
    },
    spellBlock: {
        padding: 5,
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        borderWidth: 1,
        borderColor: 'white',
        borderStyle: 'solid',
        borderRadius: 8,
    },
    addCantripButton: {
        margin: 5,
        aspectRatio: 1,
        backgroundColor: '#ffffff',
        borderRadius: 8,
        overflow: 'hidden',
        flexGrow: 0,
        flexShrink: 0,
    },
    cantripButtonBackground: {
        flex: 1,
        backgroundColor: 'black',
    },
    cantripBlock: {
        padding: 5,
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        borderWidth: 1,
        borderColor: 'white',
        borderStyle: 'solid',
        borderRadius: 8,
    },
    cantripModal: {
        backgroundColor: '#f0f0f0',
        borderRadius: 8,
        padding: 20,
        flex: 1,
        paddingTop: 60,
    },
    cantripModalContent: {
        flex: 1,
    },
    cantripModalButtonsContainer: {
        justifyContent: 'space-around',
        alignItems: 'center',
        flexDirection: 'row',
        position: 'absolute',
        bottom: 40,
        width: '100%',
        left: 20,
    },
    cantripLabel: {
        textTransform: 'uppercase',
        fontSize: 12,
        color: '#464646',
        marginBottom: 2,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    modalButton: {
        padding: 10,
        backgroundColor: 'white',
        borderRadius: 8,
    },
    modalButtonText: {
        color: 'black',
        fontSize: 16,
        fontWeight: 'bold',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 10,
    },
    headerLeft: {
        flexDirection: 'row',
        gap: 5,
    },
    headerTextContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    headerTextBox: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 8,
        padding: 5,
    },
    headerText: {
        fontSize: 12,
        color: 'white',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    footerButtonContainer: {
        borderRadius: 8,
        margin: 5,
        overflow: 'hidden',
        flex: 1,
    },
    footerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        padding: 10,
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
        borderWidth: 1,
        borderColor: 'white',
        borderStyle: 'solid',
    },
    footerButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 18,
        textTransform: 'capitalize',
    },
    headerIcons: {
        display: 'flex',
        flexDirection: 'row',
        gap: 10,
        alignItems: 'center',
    },
    headerIcon: {
        color: 'white',
    },
    resetModal: {
        margin: 20,
        backgroundColor: 'white',
        borderRadius: 8,
        padding: 20,
    },
    spellModal: {
        backgroundColor: 'white',
        borderRadius: 8,
        padding: 20,
        width: '100%',
        height: '100%',
        paddingTop: 60,
        position: 'relative',
    },
    spellModalButtonsContainer: {
        justifyContent: 'space-around',
        alignItems: 'center',
        flexDirection: 'row',
        position: 'absolute',
        bottom: 40,
        width: '100%',
        left: 20,
    },
    preparedSpellModal: {
        backgroundColor: 'white',
        borderRadius: 8,
        padding: 20,
        flexDirection: 'column',
        justifyContent: 'space-between',
        marginHorizontal: 20,
        position: 'relative',
        height: '100%',
        width: '100%',
        paddingTop: 60,
    },
    preparedSpellModalHeader: {
        fontSize: 16,
        fontWeight: 'normal',
        color: 'rgba(0, 0, 0, 0.3)',
    },
    preparedSpellModalButtonsContainer: {
        justifyContent: 'space-around',
        alignItems: 'center',
        flexDirection: 'row',
        width: '100%',
        position: 'absolute',
        bottom: 40,
        left: 20,
    },
    subheader: {
        borderRadius: 8,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 2

    },
    subheaderText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
    },
});

export default styles;